/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#0f172a",
        "primary-container": "#eff6ff",
        "error-container": "#fee2e2",
        "secondary-container": "#e2e8f0",
        "secondary-fixed": "#e2e8f0",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#bfdbfe",
        "outline": "#94a3b8",
        "surface-container-highest": "#cbd5e1",
        "on-surface-variant": "#475569",
        "on-secondary-fixed": "#0f172a",
        "on-tertiary-fixed-variant": "#4338ca",
        "tertiary-fixed": "#e0e7ff",
        "on-secondary-container": "#334155",
        "inverse-surface": "#0f172a",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#3730a3",
        "surface-variant": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "secondary": "#0f172a",
        "on-primary-fixed": "#1e3a8a",
        "background": "#f8fafc",
        "inverse-on-surface": "#f8fafc",
        "surface-bright": "#ffffff",
        "primary-fixed": "#dbeafe",
        "error": "#ef4444",
        "on-secondary-fixed-variant": "#475569",
        "on-primary-container": "#1e40af",
        "on-primary-fixed-variant": "#1d4ed8",
        "on-primary": "#ffffff",
        "on-surface": "#0f172a",
        "outline-variant": "#e2e8f0",
        "on-error": "#ffffff",
        "tertiary-container": "#eef2ff",
        "on-error-container": "#991b1b",
        "tertiary": "#4f46e5",
        "surface-tint": "#2563eb",
        "primary": "#2563eb",
        "surface": "#ffffff",
        "on-tertiary-fixed": "#312e81",
        "tertiary-fixed-dim": "#c7d2fe",
        "secondary-fixed-dim": "#cbd5e1",
        "surface-dim": "#e2e8f0",
        "inverse-primary": "#93c5fd",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "container-max": "1200px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "section-gap": "80px",
        "unit": "8px",
        "margin-desktop": "64px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-md": ["Inter", "Plus Jakarta Sans", "sans-serif"],
        "headline-md-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
}
