/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c1c",
        "primary-container": "#fadadd",
        "error-container": "#ffdad6",
        "secondary-container": "#e6e5b9",
        "secondary-fixed": "#e6e5b9",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#debfc2",
        "outline": "#807475",
        "surface-container-highest": "#e4e2e1",
        "on-surface-variant": "#4f4445",
        "on-secondary-fixed": "#1d1d03",
        "on-tertiary-fixed-variant": "#70343e",
        "tertiary-fixed": "#ffd9dd",
        "on-secondary-container": "#666643",
        "inverse-surface": "#303030",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#93505b",
        "surface-variant": "#e4e2e1",
        "surface-container-high": "#eae8e7",
        "secondary": "#60603e",
        "on-primary-fixed": "#281719",
        "background": "#fbf9f8",
        "inverse-on-surface": "#f3f0f0",
        "surface-bright": "#fbf9f8",
        "primary-fixed": "#fbdbde",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#484828",
        "on-primary-container": "#765e61",
        "on-primary-fixed-variant": "#574144",
        "on-primary": "#ffffff",
        "on-surface": "#1b1c1c",
        "outline-variant": "#d2c3c4",
        "on-error": "#ffffff",
        "tertiary-container": "#ffd8dc",
        "on-error-container": "#93000a",
        "tertiary": "#8c4b55",
        "surface-tint": "#70585b",
        "primary": "#70585b",
        "surface": "#fbf9f8",
        "on-tertiary-fixed": "#3a0915",
        "tertiary-fixed-dim": "#ffb2bc",
        "secondary-fixed-dim": "#cac99f",
        "surface-dim": "#dcd9d9",
        "inverse-primary": "#debfc2",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "container-max": "1200px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "section-gap": "80px",
        "unit": "8px",
        "margin-desktop": "64px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "label-sm": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "headline-md-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "title-sm": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
}
